baseURL: https://eugeniorss.github.io/orbitemusicali.github.io/
title: Orbite Musicali
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: false
googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
    profileMode:
        contentDir: content/posts
        enabled: true
        title: "Esplorazioni Sonore"
        subtitle: "Album per costruire un panorama musicale"
        imageUrl: "https://res.cloudinary.com/eugenio-rossini/image/upload/c_mfit,w_1024/v1670091514/theWineCellarMusic/about_me_section_wallpaper.jpg"
        imageWidth: 200 # custom size
        imageHeight: 200 # custom size
        buttons:
            - name: Posts
              url: posts
            - name: Github
              url: "https://github.com/"

    socialIcons: # optional
        - name: "<platform>"
          url: "<link>"
        - name: "<platform 2>"
          url: "<link2>"  

    gtm_id: "GTM-KJ277ZJ"
    env: production
    title: Orbite Musicali
    description: Share / Summary / Record
    keywords: [ Blog ]
    author: Eugenio Rossini
    images: []

    defaultTheme: auto # dark, light
    disableThemeToggle: false
    displayFullLangName: true

    ShowReadingTime: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: true
    tocopen: false

    assets:
      favicon: "/favicon.ico"

    socialIcons:
      - name: github
        url: "https://github.com/lexcao"
      - name: twitter
        url: "https://twitter.com/lexcao"
      - name: email
        url: "mailto:lexcao@foxmail.com"

    cover:
      hidden: false # hide everywhere but not in structured data
      hiddenInList: false # hide on list pages and home
      hiddenInSingle: false # hide on single page

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 1
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
    - identifier: about
      name: About
      url: /about/
      weight: 4
    
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags